INSERT INTO public.dict_countries(code, description, name) VALUES ("AF", "", "Afghanistan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AX", "", "land Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AL", "", "Albania");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DZ", "", "Algeria");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AS", "", "American Samoa");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AD", "", "AndorrA");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AO", "", "Angola");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AI", "", "Anguilla");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AQ", "", "Antarctica");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AG", "", "Antigua and Barbuda");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AR", "", "Argentina");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AM", "", "Armenia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AW", "", "Aruba");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AU", "", "Australia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AT", "", "Austria");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AZ", "", "Azerbaijan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BS", "", "Bahamas");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BH", "", "Bahrain");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BD", "", "Bangladesh");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BB", "", "Barbados");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BY", "", "Belarus");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BE", "", "Belgium");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BZ", "", "Belize");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BJ", "", "Benin");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BM", "", "Bermuda");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BT", "", "Bhutan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BO", "", "Bolivia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BA", "", "Bosnia and Herzegovina");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BW", "", "Botswana");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BV", "", "Bouvet Island");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BR", "", "Brazil");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IO", "", "British Indian Ocean Territory");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BN", "", "Brunei Darussalam");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BG", "", "Bulgaria");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BF", "", "Burkina Faso");
INSERT INTO public.dict_countries(code, description, name) VALUES ("BI", "", "Burundi");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KH", "", "Cambodia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CM", "", "Cameroon");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CA", "", "Canada");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CV", "", "Cape Verde");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KY", "", "Cayman Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CF", "", "Central African Republic");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TD", "", "Chad");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CL", "", "Chile");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CN", "", "China");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CX", "", "Christmas Island");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CC", "", "Cocos (Keeling) Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CO", "", "Colombia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KM", "", "Comoros");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CG", "", "Congo");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CD", "", "Congo, The Democratic Republic of the");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CK", "", "Cook Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CR", "", "Costa Rica");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CI", "", "Cote D'Ivoire");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HR", "", "Croatia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CU", "", "Cuba");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CY", "", "Cyprus");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CZ", "", "Czech Republic");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DK", "", "Denmark");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DJ", "", "Djibouti");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DM", "", "Dominica");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DO", "", "Dominican Republic");
INSERT INTO public.dict_countries(code, description, name) VALUES ("EC", "", "Ecuador");
INSERT INTO public.dict_countries(code, description, name) VALUES ("EG", "", "Egypt");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SV", "", "El Salvador");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GQ", "", "Equatorial Guinea");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ER", "", "Eritrea");
INSERT INTO public.dict_countries(code, description, name) VALUES ("EE", "", "Estonia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ET", "", "Ethiopia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FK", "", "Falkland Islands (Malvinas)");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FO", "", "Faroe Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FJ", "", "Fiji");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FI", "", "Finland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FR", "", "France");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GF", "", "French Guiana");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PF", "", "French Polynesia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TF", "", "French Southern Territories");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GA", "", "Gabon");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GM", "", "Gambia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GE", "", "Georgia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("DE", "", "Germany");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GH", "", "Ghana");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GI", "", "Gibraltar");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GR", "", "Greece");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GL", "", "Greenland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GD", "", "Grenada");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GP", "", "Guadeloupe");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GU", "", "Guam");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GT", "", "Guatemala");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GG", "", "Guernsey");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GN", "", "Guinea");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GW", "", "Guinea-Bissau");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GY", "", "Guyana");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HT", "", "Haiti");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HM", "", "Heard Island and Mcdonald Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VA", "", "Holy See (Vatican City State)");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HN", "", "Honduras");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HK", "", "Hong Kong");
INSERT INTO public.dict_countries(code, description, name) VALUES ("HU", "", "Hungary");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IS", "", "Iceland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IN", "", "India");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ID", "", "Indonesia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IR", "", "Iran, Islamic Republic Of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IQ", "", "Iraq");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IE", "", "Ireland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IM", "", "Isle of Man");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IL", "", "Israel");
INSERT INTO public.dict_countries(code, description, name) VALUES ("IT", "", "Italy");
INSERT INTO public.dict_countries(code, description, name) VALUES ("JM", "", "Jamaica");
INSERT INTO public.dict_countries(code, description, name) VALUES ("JP", "", "Japan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("JE", "", "Jersey");
INSERT INTO public.dict_countries(code, description, name) VALUES ("JO", "", "Jordan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KZ", "", "Kazakhstan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KE", "", "Kenya");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KI", "", "Kiribati");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KP", "", "Korea, Democratic People"S Republic of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KR", "", "Korea, Republic of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KW", "", "Kuwait");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KG", "", "Kyrgyzstan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LA", "", "Lao People"S Democratic Republic");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LV", "", "Latvia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LB", "", "Lebanon");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LS", "", "Lesotho");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LR", "", "Liberia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LY", "", "Libyan Arab Jamahiriya");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LI", "", "Liechtenstein");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LT", "", "Lithuania");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LU", "", "Luxembourg");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MO", "", "Macao");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MK", "", "Macedonia, The Former Yugoslav Republic of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MG", "", "Madagascar");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MW", "", "Malawi");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MY", "", "Malaysia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MV", "", "Maldives");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ML", "", "Mali");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MT", "", "Malta");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MH", "", "Marshall Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MQ", "", "Martinique");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MR", "", "Mauritania");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MU", "", "Mauritius");
INSERT INTO public.dict_countries(code, description, name) VALUES ("YT", "", "Mayotte");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MX", "", "Mexico");
INSERT INTO public.dict_countries(code, description, name) VALUES ("FM", "", "Micronesia, Federated States of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MD", "", "Moldova, Republic of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MC", "", "Monaco");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MN", "", "Mongolia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ME", "", "Montenegro");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MS", "", "Montserrat");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MA", "", "Morocco");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MZ", "", "Mozambique");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MM", "", "Myanmar");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NA", "", "Namibia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NR", "", "Nauru");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NP", "", "Nepal");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NL", "", "Netherlands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AN", "", "Netherlands Antilles");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NC", "", "New Caledonia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NZ", "", "New Zealand");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NI", "", "Nicaragua");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NE", "", "Niger");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NG", "", "Nigeria");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NU", "", "Niue");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NF", "", "Norfolk Island");
INSERT INTO public.dict_countries(code, description, name) VALUES ("MP", "", "Northern Mariana Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("NO", "", "Norway");
INSERT INTO public.dict_countries(code, description, name) VALUES ("OM", "", "Oman");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PK", "", "Pakistan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PW", "", "Palau");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PS", "", "Palestinian Territory, Occupied");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PA", "", "Panama");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PG", "", "Papua New Guinea");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PY", "", "Paraguay");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PE", "", "Peru");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PH", "", "Philippines");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PN", "", "Pitcairn");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PL", "", "Poland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PT", "", "Portugal");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PR", "", "Puerto Rico");
INSERT INTO public.dict_countries(code, description, name) VALUES ("QA", "", "Qatar");
INSERT INTO public.dict_countries(code, description, name) VALUES ("RE", "", "Reunion");
INSERT INTO public.dict_countries(code, description, name) VALUES ("RO", "", "Romania");
INSERT INTO public.dict_countries(code, description, name) VALUES ("RU", "", "Russian Federation");
INSERT INTO public.dict_countries(code, description, name) VALUES ("RW", "", "RWANDA");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SH", "", "Saint Helena");
INSERT INTO public.dict_countries(code, description, name) VALUES ("KN", "", "Saint Kitts and Nevis");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LC", "", "Saint Lucia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("PM", "", "Saint Pierre and Miquelon");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VC", "", "Saint Vincent and the Grenadines");
INSERT INTO public.dict_countries(code, description, name) VALUES ("WS", "", "Samoa");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SM", "", "San Marino");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ST", "", "Sao Tome and Principe");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SA", "", "Saudi Arabia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SN", "", "Senegal");
INSERT INTO public.dict_countries(code, description, name) VALUES ("RS", "", "Serbia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SC", "", "Seychelles");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SL", "", "Sierra Leone");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SG", "", "Singapore");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SK", "", "Slovakia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SI", "", "Slovenia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SB", "", "Solomon Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SO", "", "Somalia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ZA", "", "South Africa");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GS", "", "South Georgia and the South Sandwich Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ES", "", "Spain");
INSERT INTO public.dict_countries(code, description, name) VALUES ("LK", "", "Sri Lanka");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SD", "", "Sudan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SR", "", "Suriname");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SJ", "", "Svalbard and Jan Mayen");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SZ", "", "Swaziland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SE", "", "Sweden");
INSERT INTO public.dict_countries(code, description, name) VALUES ("CH", "", "Switzerland");
INSERT INTO public.dict_countries(code, description, name) VALUES ("SY", "", "Syrian Arab Republic");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TW", "", "Taiwan, Province of China");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TJ", "", "Tajikistan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TZ", "", "Tanzania, United Republic of");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TH", "", "Thailand");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TL", "", "Timor-Leste");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TG", "", "Togo");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TK", "", "Tokelau");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TO", "", "Tonga");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TT", "", "Trinidad and Tobago");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TN", "", "Tunisia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TR", "", "Turkey");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TM", "", "Turkmenistan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TC", "", "Turks and Caicos Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("TV", "", "Tuvalu");
INSERT INTO public.dict_countries(code, description, name) VALUES ("UG", "", "Uganda");
INSERT INTO public.dict_countries(code, description, name) VALUES ("UA", "", "Ukraine");
INSERT INTO public.dict_countries(code, description, name) VALUES ("AE", "", "United Arab Emirates");
INSERT INTO public.dict_countries(code, description, name) VALUES ("GB", "", "United Kingdom");
INSERT INTO public.dict_countries(code, description, name) VALUES ("US", "", "United States");
INSERT INTO public.dict_countries(code, description, name) VALUES ("UM", "", "United States Minor Outlying Islands");
INSERT INTO public.dict_countries(code, description, name) VALUES ("UY", "", "Uruguay");
INSERT INTO public.dict_countries(code, description, name) VALUES ("UZ", "", "Uzbekistan");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VU", "", "Vanuatu");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VE", "", "Venezuela");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VN", "", "Viet Nam");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VG", "", "Virgin Islands, British");
INSERT INTO public.dict_countries(code, description, name) VALUES ("VI", "", "Virgin Islands, U.S.");
INSERT INTO public.dict_countries(code, description, name) VALUES ("WF", "", "Wallis and Futuna");
INSERT INTO public.dict_countries(code, description, name) VALUES ("EH", "", "Western Sahara");
INSERT INTO public.dict_countries(code, description, name) VALUES ("YE", "", "Yemen");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ZM", "", "Zambia");
INSERT INTO public.dict_countries(code, description, name) VALUES ("ZW", "", "Zimbabwe");
