INSERT INTO public.dict_countries(code, description, name) VALUES ('AF', null, 'Afghanistan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AX', null, 'land Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AL', null, 'Albania');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DZ', null, 'Algeria');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AS', null, 'American Samoa');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AD', null, 'AndorrA');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AO', null, 'Angola');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AI', null, 'Anguilla');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AQ', null, 'Antarctica');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AG', null, 'Antigua and Barbuda');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AR', null, 'Argentina');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AM', null, 'Armenia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AW', null, 'Aruba');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AU', null, 'Australia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AT', null, 'Austria');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AZ', null, 'Azerbaijan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BS', null, 'Bahamas');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BH', null, 'Bahrain');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BD', null, 'Bangladesh');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BB', null, 'Barbados');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BY', null, 'Belarus');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BE', null, 'Belgium');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BZ', null, 'Belize');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BJ', null, 'Benin');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BM', null, 'Bermuda');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BT', null, 'Bhutan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BO', null, 'Bolivia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BA', null, 'Bosnia and Herzegovina');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BW', null, 'Botswana');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BV', null, 'Bouvet Island');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BR', null, 'Brazil');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IO', null, 'British Indian Ocean Territory');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BN', null, 'Brunei Darussalam');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BG', null, 'Bulgaria');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BF', null, 'Burkina Faso');
INSERT INTO public.dict_countries(code, description, name) VALUES ('BI', null, 'Burundi');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KH', null, 'Cambodia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CM', null, 'Cameroon');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CA', null, 'Canada');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CV', null, 'Cape Verde');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KY', null, 'Cayman Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CF', null, 'Central African Republic');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TD', null, 'Chad');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CL', null, 'Chile');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CN', null, 'China');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CX', null, 'Christmas Island');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CC', null, 'Cocos (Keeling) Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CO', null, 'Colombia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KM', null, 'Comoros');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CG', null, 'Congo');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CD', null, 'Congo, The Democratic Republic of the');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CK', null, 'Cook Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CR', null, 'Costa Rica');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CI', null, 'Cote D''Ivoire');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HR', null, 'Croatia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CU', null, 'Cuba');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CY', null, 'Cyprus');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CZ', null, 'Czech Republic');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DK', null, 'Denmark');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DJ', null, 'Djibouti');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DM', null, 'Dominica');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DO', null, 'Dominican Republic');
INSERT INTO public.dict_countries(code, description, name) VALUES ('EC', null, 'Ecuador');
INSERT INTO public.dict_countries(code, description, name) VALUES ('EG', null, 'Egypt');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SV', null, 'El Salvador');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GQ', null, 'Equatorial Guinea');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ER', null, 'Eritrea');
INSERT INTO public.dict_countries(code, description, name) VALUES ('EE', null, 'Estonia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ET', null, 'Ethiopia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FK', null, 'Falkland Islands (Malvinas)');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FO', null, 'Faroe Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FJ', null, 'Fiji');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FI', null, 'Finland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FR', null, 'France');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GF', null, 'French Guiana');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PF', null, 'French Polynesia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TF', null, 'French Southern Territories');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GA', null, 'Gabon');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GM', null, 'Gambia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GE', null, 'Georgia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('DE', null, 'Germany');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GH', null, 'Ghana');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GI', null, 'Gibraltar');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GR', null, 'Greece');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GL', null, 'Greenland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GD', null, 'Grenada');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GP', null, 'Guadeloupe');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GU', null, 'Guam');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GT', null, 'Guatemala');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GG', null, 'Guernsey');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GN', null, 'Guinea');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GW', null, 'Guinea-Bissau');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GY', null, 'Guyana');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HT', null, 'Haiti');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HM', null, 'Heard Island and Mcdonald Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VA', null, 'Holy See (Vatican City State)');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HN', null, 'Honduras');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HK', null, 'Hong Kong');
INSERT INTO public.dict_countries(code, description, name) VALUES ('HU', null, 'Hungary');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IS', null, 'Iceland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IN', null, 'India');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ID', null, 'Indonesia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IR', null, 'Iran, Islamic Republic Of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IQ', null, 'Iraq');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IE', null, 'Ireland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IM', null, 'Isle of Man');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IL', null, 'Israel');
INSERT INTO public.dict_countries(code, description, name) VALUES ('IT', null, 'Italy');
INSERT INTO public.dict_countries(code, description, name) VALUES ('JM', null, 'Jamaica');
INSERT INTO public.dict_countries(code, description, name) VALUES ('JP', null, 'Japan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('JE', null, 'Jersey');
INSERT INTO public.dict_countries(code, description, name) VALUES ('JO', null, 'Jordan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KZ', null, 'Kazakhstan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KE', null, 'Kenya');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KI', null, 'Kiribati');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KP', null, 'Korea, Democratic People''S Republic of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KR', null, 'Korea, Republic of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KW', null, 'Kuwait');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KG', null, 'Kyrgyzstan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LA', null, 'Lao People''S Democratic Republic');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LV', null, 'Latvia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LB', null, 'Lebanon');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LS', null, 'Lesotho');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LR', null, 'Liberia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LY', null, 'Libyan Arab Jamahiriya');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LI', null, 'Liechtenstein');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LT', null, 'Lithuania');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LU', null, 'Luxembourg');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MO', null, 'Macao');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MK', null, 'Macedonia, The Former Yugoslav Republic of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MG', null, 'Madagascar');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MW', null, 'Malawi');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MY', null, 'Malaysia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MV', null, 'Maldives');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ML', null, 'Mali');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MT', null, 'Malta');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MH', null, 'Marshall Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MQ', null, 'Martinique');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MR', null, 'Mauritania');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MU', null, 'Mauritius');
INSERT INTO public.dict_countries(code, description, name) VALUES ('YT', null, 'Mayotte');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MX', null, 'Mexico');
INSERT INTO public.dict_countries(code, description, name) VALUES ('FM', null, 'Micronesia, Federated States of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MD', null, 'Moldova, Republic of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MC', null, 'Monaco');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MN', null, 'Mongolia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ME', null, 'Montenegro');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MS', null, 'Montserrat');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MA', null, 'Morocco');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MZ', null, 'Mozambique');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MM', null, 'Myanmar');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NA', null, 'Namibia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NR', null, 'Nauru');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NP', null, 'Nepal');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NL', null, 'Netherlands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AN', null, 'Netherlands Antilles');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NC', null, 'New Caledonia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NZ', null, 'New Zealand');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NI', null, 'Nicaragua');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NE', null, 'Niger');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NG', null, 'Nigeria');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NU', null, 'Niue');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NF', null, 'Norfolk Island');
INSERT INTO public.dict_countries(code, description, name) VALUES ('MP', null, 'Northern Mariana Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('NO', null, 'Norway');
INSERT INTO public.dict_countries(code, description, name) VALUES ('OM', null, 'Oman');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PK', null, 'Pakistan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PW', null, 'Palau');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PS', null, 'Palestinian Territory, Occupied');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PA', null, 'Panama');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PG', null, 'Papua New Guinea');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PY', null, 'Paraguay');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PE', null, 'Peru');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PH', null, 'Philippines');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PN', null, 'Pitcairn');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PL', null, 'Poland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PT', null, 'Portugal');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PR', null, 'Puerto Rico');
INSERT INTO public.dict_countries(code, description, name) VALUES ('QA', null, 'Qatar');
INSERT INTO public.dict_countries(code, description, name) VALUES ('RE', null, 'Reunion');
INSERT INTO public.dict_countries(code, description, name) VALUES ('RO', null, 'Romania');
INSERT INTO public.dict_countries(code, description, name) VALUES ('RU', null, 'Russian Federation');
INSERT INTO public.dict_countries(code, description, name) VALUES ('RW', null, 'RWANDA');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SH', null, 'Saint Helena');
INSERT INTO public.dict_countries(code, description, name) VALUES ('KN', null, 'Saint Kitts and Nevis');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LC', null, 'Saint Lucia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('PM', null, 'Saint Pierre and Miquelon');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VC', null, 'Saint Vincent and the Grenadines');
INSERT INTO public.dict_countries(code, description, name) VALUES ('WS', null, 'Samoa');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SM', null, 'San Marino');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ST', null, 'Sao Tome and Principe');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SA', null, 'Saudi Arabia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SN', null, 'Senegal');
INSERT INTO public.dict_countries(code, description, name) VALUES ('RS', null, 'Serbia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SC', null, 'Seychelles');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SL', null, 'Sierra Leone');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SG', null, 'Singapore');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SK', null, 'Slovakia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SI', null, 'Slovenia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SB', null, 'Solomon Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SO', null, 'Somalia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ZA', null, 'South Africa');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GS', null, 'South Georgia and the South Sandwich Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ES', null, 'Spain');
INSERT INTO public.dict_countries(code, description, name) VALUES ('LK', null, 'Sri Lanka');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SD', null, 'Sudan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SR', null, 'Suriname');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SJ', null, 'Svalbard and Jan Mayen');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SZ', null, 'Swaziland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SE', null, 'Sweden');
INSERT INTO public.dict_countries(code, description, name) VALUES ('CH', null, 'Switzerland');
INSERT INTO public.dict_countries(code, description, name) VALUES ('SY', null, 'Syrian Arab Republic');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TW', null, 'Taiwan, Province of China');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TJ', null, 'Tajikistan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TZ', null, 'Tanzania, United Republic of');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TH', null, 'Thailand');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TL', null, 'Timor-Leste');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TG', null, 'Togo');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TK', null, 'Tokelau');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TO', null, 'Tonga');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TT', null, 'Trinidad and Tobago');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TN', null, 'Tunisia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TR', null, 'Turkey');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TM', null, 'Turkmenistan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TC', null, 'Turks and Caicos Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('TV', null, 'Tuvalu');
INSERT INTO public.dict_countries(code, description, name) VALUES ('UG', null, 'Uganda');
INSERT INTO public.dict_countries(code, description, name) VALUES ('UA', null, 'Ukraine');
INSERT INTO public.dict_countries(code, description, name) VALUES ('AE', null, 'United Arab Emirates');
INSERT INTO public.dict_countries(code, description, name) VALUES ('GB', null, 'United Kingdom');
INSERT INTO public.dict_countries(code, description, name) VALUES ('US', null, 'United States');
INSERT INTO public.dict_countries(code, description, name) VALUES ('UM', null, 'United States Minor Outlying Islands');
INSERT INTO public.dict_countries(code, description, name) VALUES ('UY', null, 'Uruguay');
INSERT INTO public.dict_countries(code, description, name) VALUES ('UZ', null, 'Uzbekistan');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VU', null, 'Vanuatu');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VE', null, 'Venezuela');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VN', null, 'Viet Nam');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VG', null, 'Virgin Islands, British');
INSERT INTO public.dict_countries(code, description, name) VALUES ('VI', null, 'Virgin Islands, U.S.');
INSERT INTO public.dict_countries(code, description, name) VALUES ('WF', null, 'Wallis and Futuna');
INSERT INTO public.dict_countries(code, description, name) VALUES ('EH', null, 'Western Sahara');
INSERT INTO public.dict_countries(code, description, name) VALUES ('YE', null, 'Yemen');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ZM', null, 'Zambia');
INSERT INTO public.dict_countries(code, description, name) VALUES ('ZW', null, 'Zimbabwe');
